### ISSUE TITLE
CI not finding 'example' tests after installation

### ISSUE THREAD

**Issue by puneetmatharu** [scivision/scalapack#3]
I'm currently using a fork of this repository; whilst debugging a couple of issues with the CI, I found some things worth flagging up:
1. I compared the Actions that were run in my fork against your repository and found that your CI does not find any tests to run after configuring/building the `examples/` folder, and;
2. The number of procs required by these examples (i.e. 4 or 6) is greater than the number available on the GitHub runners. It may be worth simplifying the examples to use 2 procs maximum.

**Comment by scivision** [comment]
I didn't have time to rewrite the examples, but I added a 2-core test and disabled tests if not enough CPU cores. I also made the CI fail if no tests run.

c180ae76
